### ISSUE TITLE
"Failed to get a response!" error

### ISSUE THREAD

**Issue by Half-Time** [IntriguingTiles/hgrunt-bot#13]
This already happened, it's not just in one server, it's in every single server, sometimes it just decides to not work and says **"Failed to get a response!"**. It already happened and we had to wait 3 months for it to work again. Other commands work correctly.
![HGrunt error](https://user-images.githubusercontent.com/98899935/152188465-e1a12ae5-2c5e-4251-813d-d62aa104686f.jpg)

**Comment by IntriguingTiles** [comment]
This should be fixed now.
