### ISSUE TITLE
Another "Failed to get a response!" error

### ISSUE THREAD

**Issue by Half-Time** [IntriguingTiles/hgrunt-bot#26]
He's doing it again. No idea how long has the bot been "dead".
![image](https://github.com/IntriguingTiles/hgrunt-bot/assets/98899935/1257ac20-6c4b-465b-8b3d-6af19e53a579)

**Comment by IntriguingTiles** [comment]
Cleverbot has blocked my server's IPv6 address, which I can get around by forcing my server to get a new IPv6 address but it ends up resetting to the old one on reboot. I've fixed this for now.
